version: '3.8'
services:
    deskbird-redis:
        image: redis:5
        ports:
            - '6379:6379'

    deskbird-database:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: emulator
